
############################## VOLUMES #########################################


volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/rabouzia/data/mariadb


  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/rabouzia/data/wordpress


  mc:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/rabouzia/data/minecraft


  adm:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/rabouzia/data/adminer



############################## MANDATORY #########################################


##############################  SERVICE #########################################

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    env_file: .env



  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    restart: always
    networks:
      - inception
    depends_on:
      - nginx
    env_file: .env
    ports:
      - "80:80" 


  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    env_file: .env
    stdin_open: true
    tty: true



  nginx:
    container_name: nginx
    build: requirements/nginx/.
    restart: always
    volumes:
     - wp:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception


############################## BONUS #########################################


  redis:
    container_name: redis
    build: requirements/bonus/redis
    restart: always
    networks:
      - inception
    env_file: .env



  # ftp:
  #   container_name: ftp
  #   build: requirements/bonus/ftp
  #   restart: always
  #   networks:
  #     - inception
  #   ports:
  #     - "20:20"
  #     - "21:21"
  #     - "40000-40050:40000-40050"
  #   env_file: .env



  static_web:
    container_name: static_web
    build: requirements/bonus/static_web
    restart: always
    networks:
      - inception
    ports:
      - "3000:3000"



  minecraft:
    container_name: minecraft
    build: requirements/bonus/minecraft
    restart: always
    networks:
      - inception
    ports:
      - "25565:25565"
    volumes:
      - mc:/home/rabouzia/data/minecraft



############################## NETWORK #########################################

networks:
  inception:
    name : inception
    driver : bridge
