services:
  adminer:
    container_name: Adminer
    build: requirements/adminer/.
    restart: always
    networks:
      - mynetwork
  
  mariadb:
    container_name: Mariadb
    build: requirements/mariadb/.
    restart: always
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file: /Users/ramzerk/.env
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - mynetwork
    volumes:
      - wp:/var/www/html
    env_file: /Users/ramzerk/.env
    stdin_open: true
    tty: true
  
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    restart: always
    volumes:
     - wp:/var/www/html
    depends_on:
      - wordpress
      - adminer
    ports:
      - "443:443"
      - "80:80"
      - "25565:25565"
    networks:
      - mynetwork


networks:
  mynetwork:
    name : mynetwork
    driver : bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./my_volume
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./my_volume